window.CARD_DATA = [
  { italian: "burro", french: "beurre", english: "butter", notes: "Also means donkey.", category: "false-friends" },
  { italian: "camera", french: "chambre", english: "room", notes: "Not caméra. That is macchina fotografica.", category: "false-friends" },
  { italian: "macchina fotografica", french: "appareil photo", english: "camera", notes: "", category: "vocab" },
  { italian: "guardare", french: "regarder", english: "to look/watch", notes: "Not garder, which means to keep.", category: "false-friends" },
  { italian: "salire", french: "monter", english: "to go up/climb", notes: "Not salir, which means to dirty.", category: "false-friends" },
  { italian: "scendere", french: "descendre", english: "to go down", notes: "", category: "vocab" },
  { italian: "uscire", french: "sortir", english: "to go out/exit", notes: "", category: "vocab" },
  { italian: "subito", french: "tout de suite", english: "immediately", notes: "Not soudain, which means suddenly.", category: "false-friends" },
  { italian: "magazzino", french: "entrepôt", english: "warehouse", notes: "Not magasin. That is negozio.", category: "false-friends" },
  { italian: "negozio", french: "magasin", english: "store/shop", notes: "", category: "vocab" },
  { italian: "parente", french: "parent/membre de la famille", english: "relative", notes: "Not parent. Use genitore for parent.", category: "false-friends" },
  { italian: "genitore", french: "parent", english: "parent", notes: "", category: "vocab" },
  { italian: "padre", french: "père", english: "father", notes: "", category: "vocab" },
  { italian: "madre", french: "mère", english: "mother", notes: "", category: "vocab" },
  { italian: "rumore", french: "bruit", english: "noise", notes: "Not rumeur. That is voce.", category: "false-friends" },
  { italian: "voce", french: "rumeur/voix", english: "rumor/voice", notes: "", category: "vocab" },
  { italian: "resto", french: "monnaie/reste", english: "change (money)/rest", notes: "", category: "vocab" },
  { italian: "mancia", french: "pourboire", english: "tip (gratuity)", notes: "", category: "vocab" },
  { italian: "firma", french: "signature", english: "signature", notes: "Not firme, which means company.", category: "false-friends" },
  { italian: "presto", french: "tôt/bientôt/vite", english: "early/soon/quickly", notes: "Not prêt, which means ready.", category: "false-friends" },
  { italian: "fastidioso", french: "énervant/agaçant", english: "annoying", notes: "Not fastidieux. That is noioso.", category: "false-friends" },
  { italian: "noioso", french: "ennuyeux", english: "boring", notes: "", category: "vocab" },
  { italian: "pretendere", french: "exiger", english: "to demand/expect", notes: "Not prétendre, which means to claim.", category: "false-friends" },
  { italian: "fingere", french: "faire semblant", english: "to pretend", notes: "", category: "vocab" },
  { italian: "controllare", french: "vérifier", english: "to check/verify", notes: "Not just contrôler.", category: "false-friends" },
  { italian: "guidare", french: "conduire", english: "to drive", notes: "Not guider, which means to guide.", category: "false-friends" },
  { italian: "fermare", french: "arrêter", english: "to stop", notes: "Not fermer. That is chiudere.", category: "false-friends" },
  { italian: "chiudere", french: "fermer", english: "to close", notes: "", category: "vocab" },
  { italian: "imbarazzato", french: "embarrassé", english: "embarrassed", notes: "Not pregnant. That is incinta.", category: "false-friends" },
  { italian: "incinta", french: "enceinte", english: "pregnant", notes: "", category: "vocab" },
  { italian: "eccitato", french: "excité", english: "excited", notes: "Can have a sexual connotation. Use emozionato instead.", category: "false-friends" },
  { italian: "emozionato", french: "ému/excité", english: "excited/moved", notes: "Safer choice.", category: "vocab" },
  { italian: "sensibile", french: "sensible", english: "sensitive", notes: "Not sensible/reasonable. That is sensato.", category: "false-friends" },
  { italian: "sensato", french: "raisonnable", english: "sensible/reasonable", notes: "", category: "vocab" },
  { italian: "adesso", french: "maintenant", english: "now", notes: "", category: "vocab" },
  { italian: "ora", french: "maintenant", english: "now", notes: "", category: "vocab" },
  { italian: "tardi", french: "tard", english: "late", notes: "", category: "vocab" },
  { italian: "sempre", french: "toujours", english: "always", notes: "", category: "vocab" },
  { italian: "mai", french: "jamais", english: "never/ever", notes: "", category: "vocab" },
  { italian: "ancora", french: "encore", english: "still/again", notes: "", category: "vocab" },
  { italian: "già", french: "déjà", english: "already", notes: "", category: "vocab" },
  { italian: "spesso", french: "souvent", english: "often", notes: "", category: "vocab" },
  { italian: "capire", french: "comprendre", english: "to understand", notes: "", category: "vocab" },
  { italian: "sentire", french: "entendre/sentir", english: "to hear/feel", notes: "", category: "vocab" },
  { italian: "ascoltare", french: "écouter", english: "to listen", notes: "", category: "vocab" },
  { italian: "vedere", french: "voir", english: "to see", notes: "", category: "vocab" },
  { italian: "cercare", french: "chercher", english: "to look for", notes: "", category: "vocab" },
  { italian: "trovare", french: "trouver", english: "to find", notes: "", category: "vocab" },
  { italian: "perdere", french: "perdre", english: "to lose", notes: "", category: "vocab" },
  { italian: "vincere", french: "gagner", english: "to win", notes: "", category: "vocab" },
  { italian: "lasciare", french: "laisser", english: "to leave/let", notes: "", category: "vocab" },
  { italian: "partire", french: "partir", english: "to leave/depart", notes: "", category: "vocab" },
  { italian: "tornare", french: "revenir/retourner", english: "to return", notes: "", category: "vocab" },
  { italian: "rimanere", french: "rester", english: "to stay/remain", notes: "", category: "vocab" },
  { italian: "succedere", french: "arriver/se passer", english: "to happen", notes: "", category: "vocab" },
  { italian: "cambiare", french: "changer", english: "to change", notes: "", category: "vocab" },
  { italian: "ricordare", french: "se souvenir", english: "to remember", notes: "", category: "vocab" },
  { italian: "dimenticare", french: "oublier", english: "to forget", notes: "", category: "vocab" },
  { italian: "scegliere", french: "choisir", english: "to choose", notes: "", category: "vocab" },
  { italian: "cibo", french: "nourriture", english: "food", notes: "", category: "vocab" },
  { italian: "pasto", french: "repas", english: "meal", notes: "", category: "vocab" },
  { italian: "colazione", french: "petit-déjeuner", english: "breakfast", notes: "Not déjeuner. That is pranzo.", category: "false-friends" },
  { italian: "pranzo", french: "déjeuner", english: "lunch", notes: "", category: "vocab" },
  { italian: "cena", french: "dîner", english: "dinner", notes: "", category: "vocab" },
  { italian: "bagno", french: "salle de bain", english: "bathroom", notes: "", category: "vocab" },
  { italian: "camera da letto", french: "chambre", english: "bedroom", notes: "", category: "vocab" },
  { italian: "salotto", french: "salon", english: "living room", notes: "", category: "vocab" },
  { italian: "cucina", french: "cuisine", english: "kitchen", notes: "", category: "vocab" },
  { italian: "acqua", french: "eau", english: "water", notes: "", category: "vocab" },
  { italian: "vino", french: "vin", english: "wine", notes: "", category: "vocab" },
  { italian: "birra", french: "bière", english: "beer", notes: "", category: "vocab" },
  { italian: "caffè", french: "café", english: "coffee", notes: "", category: "vocab" },
  { italian: "latte", french: "lait", english: "milk", notes: "", category: "vocab" },
  { italian: "pane", french: "pain", english: "bread", notes: "", category: "vocab" },
  { italian: "formaggio", french: "fromage", english: "cheese", notes: "", category: "vocab" },
  { italian: "carne", french: "viande", english: "meat", notes: "", category: "vocab" },
  { italian: "pesce", french: "poisson", english: "fish", notes: "", category: "vocab" },
  { italian: "verdura", french: "légume", english: "vegetable", notes: "", category: "vocab" },
  { italian: "frutta", french: "fruit", english: "fruit", notes: "", category: "vocab" },
  { italian: "testa", french: "tête", english: "head", notes: "", category: "vocab" },
  { italian: "occhio", french: "œil", english: "eye", notes: "", category: "vocab" },
  { italian: "mano", french: "main", english: "hand", notes: "", category: "vocab" },
  { italian: "piede", french: "pied", english: "foot", notes: "", category: "vocab" },
  { italian: "persona", french: "personne", english: "person", notes: "", category: "vocab" },
  { italian: "uomo", french: "homme", english: "man", notes: "", category: "vocab" },
  { italian: "donna", french: "femme", english: "woman", notes: "", category: "vocab" },
  { italian: "bambino", french: "enfant", english: "child", notes: "", category: "vocab" },
  { italian: "ragazzo", french: "garçon", english: "boy/young man", notes: "", category: "vocab" },
  { italian: "ragazza", french: "fille", english: "girl/young woman", notes: "", category: "vocab" },
  { italian: "amico", french: "ami", english: "friend", notes: "", category: "vocab" },
  { italian: "città", french: "ville", english: "city", notes: "", category: "vocab" },
  { italian: "paese", french: "pays/village", english: "country/village", notes: "Context matters.", category: "vocab" },
  { italian: "strada", french: "rue", english: "street", notes: "", category: "vocab" },
  { italian: "casa", french: "maison", english: "house/home", notes: "", category: "vocab" },
  { italian: "scuola", french: "école", english: "school", notes: "", category: "vocab" },
  { italian: "lavoro", french: "travail", english: "work", notes: "", category: "vocab" },
  { italian: "macchina", french: "voiture", english: "car", notes: "Not machine.", category: "false-friends" },
  { italian: "giorno", french: "jour", english: "day", notes: "", category: "vocab" },
  { italian: "settimana", french: "semaine", english: "week", notes: "", category: "vocab" },
  { italian: "mese", french: "mois", english: "month", notes: "", category: "vocab" },
  { italian: "anno", french: "an/année", english: "year", notes: "", category: "vocab" },
  { italian: "buono", french: "bon", english: "good", notes: "", category: "vocab" },
  { italian: "cattivo", french: "mauvais", english: "bad", notes: "", category: "vocab" },
  { italian: "bello", french: "beau", english: "beautiful", notes: "", category: "vocab" },
  { italian: "grande", french: "grand", english: "big", notes: "", category: "vocab" },
  { italian: "piccolo", french: "petit", english: "small", notes: "", category: "vocab" },
  { italian: "nuovo", french: "nouveau", english: "new", notes: "", category: "vocab" },
  { italian: "vecchio", french: "vieux", english: "old", notes: "", category: "vocab" },
  { italian: "felice", french: "heureux", english: "happy", notes: "", category: "vocab" },
  { italian: "triste", french: "triste", english: "sad", notes: "", category: "vocab" },
  { italian: "bianco", french: "blanc", english: "white", notes: "", category: "vocab" },
  { italian: "nero", french: "noir", english: "black", notes: "", category: "vocab" },
  { italian: "rosso", french: "rouge", english: "red", notes: "", category: "vocab" },
  { italian: "blu", french: "bleu", english: "blue", notes: "", category: "vocab" },
  { italian: "verde", french: "vert", english: "green", notes: "", category: "vocab" },
  { italian: "giallo", french: "jaune", english: "yellow", notes: "", category: "vocab" }
];
